# dbt_demo:
#   outputs:
#     dev: # these names can be anything you like
#       dbname: bootcamp_db
#       host: 10.20.1.50
#       pass: bootcamp_password
#       port: 5432
#       schema: public
#       threads: 5
#       type: postgres
#       user: bootcamp_user
#   target: dev


dbt_lake:
  target: dev
  outputs:
    dev:
      type: athena
      region_name: ap-southeast-2
      work_group: primary
      database: AwsDataCatalog
      schema: raw
      s3_staging_dir: s3://data-lake-dev-buya/raw/athena/staging
      s3_data_dir: s3://data-lake-dev-buya/raw/
      threads: 5