
# description of the staging schema for dbt_demo project
version: 2

models:
  - name:  customers
    description: "Customers with full name and email"
    columns:
      - name: customer_code
        description: "The primary key for this table"
        data_tests:
          - not_null
          - unique
  - name:  hist_customers
    description: "Customers with full name and email"
    columns:
      - name: customer_code
        description: "The primary key for this table"
        data_tests:
          - not_null
          - unique
  - name:  accounts
    description: "Customers accounts on warehouse"
    columns:
      - name: account_id
        description: "The primary key for this table"
        data_tests:
          - not_null
          - unique
  - name:  transactions
    description: "Customers transactions on warehouse"
    columns:
      - name: transaction_id
        description: "The primary key for this table"
        data_tests:
          - not_null
          - unique
        