dbt_capstone:
  outputs:
    dev:
      dbname: bootcamp_db
      host: localhost
      pass: password
      port: 5432
      schema: public
      threads: 5
      type: postgres
      user: user
  target: dev
# dbt_demo:
#   outputs:
#     dev:
#       dbname: bootcamp_db
#       host: localhost
#       pass: boot
#       port: 5432
#       schema: public
#       threads: 5
#       type: postgres
#       user: user
#   target: dev
